Repository thematters/matters-web, pull requests merged in 2020-12, with the labels that each got.

#1643 Upgrade to Next.js 10 and React 17 and other deps;
  package-lock.json
  package.json
  postcss.config.js
  src/common/enums/route.ts
  src/common/utils/analytics.ts
  src/common/utils/route.ts
  src/components/Analytics/index.ts
  src/components/ArticleDigest/Dropdown/OpenExternalLink.tsx
  src/components/ArticleDigest/Dropdown/index.tsx
  src/components/ArticleDigest/DropdownActions/EditButton.tsx
  src/components/ArticleDigest/DropdownActions/ExtendButton.tsx
  src/components/ArticleDigest/FooterActions/index.tsx
  src/components/Button/index.tsx
  src/components/Buttons/Write/index.tsx
  src/components/Dialog/Dialog.tsx
  src/components/Dialogs/AppreciatorsDialog/Content.tsx
  src/components/Dialogs/TagDialog/Content.tsx
  src/components/Form/List/Item/index.tsx
  src/components/GQL/error.tsx
  src/components/Interaction/Card/index.tsx
  src/components/Interaction/LinkWrapper/index.tsx
  src/components/Layout/Header/BackButton/index.tsx
  src/components/Layout/Header/MeButton/SideDrawerNav/index.tsx
  src/components/OnboardingTasks/Tasks/TaskItem/index.tsx
  src/components/OnboardingTasks/Tasks/index.tsx
  src/components/Popper/index.tsx
  src/components/Search/SearchAutoComplete/index.tsx
  src/components/Search/SearchBar/index.tsx
  src/components/SearchSelect/SearchingArea/index.tsx
  src/pages/recommendation.tsx
  src/views/ArticleDetail/EditMode/PublishState/PublishedState.tsx
  src/views/ArticleDetail/index.tsx
  src/views/Follow/FollowFeed/ArticlesFeed/index.tsx
  src/views/Follow/FollowFeed/CommentsFeed/index.tsx
  src/views/Follow/FollowFeed/DonationsFeed/index.tsx
  src/views/Follow/FollowFeed/TagsFeed/index.tsx
  src/views/Me/AppreciationsReceived/index.tsx
  src/views/Me/DraftDetail/PublishState/PublishedState.tsx
  src/views/Me/Settings/Blocked/SettingsBlocked.tsx
  src/views/Migration/Features.tsx
  src/views/Search/AggregateResults/Articles.tsx
  src/views/Search/SearchTags/index.tsx
  src/views/Search/index.tsx
  src/views/TagDetail/Buttons/AddButton/CreateDraftMenuItem/index.tsx
  src/views/TagDetail/index.tsx
  src/views/Tags/index.tsx
Labels: ready

#1674 fix(onboarding-tasks): store init state separately based on viewer id
  src/common/enums/events.ts
  src/common/utils/resolvers/clientPreference.ts
  src/components/ClientUpdater/index.tsx
  src/components/GlobalDialogs/TermAlertDialog/index.tsx
  src/components/Layout/NavMenu/Bottom.tsx
  src/components/Root/index.tsx
Labels: ready

#1675 Fix <LikeCoinDialog> auto closed on Liker ID finish setup
  src/components/Buttons/Write/index.tsx
  src/components/Comment/FooterActions/index.tsx
  src/components/GlobalDialogs/index.tsx
  src/components/OnboardingTasks/Tasks/index.tsx
  src/views/ArticleDetail/AppreciationButton/SetupLikerIdAppreciateButton.tsx
  src/views/ArticleDetail/Donation/index.tsx
  src/views/ArticleDetail/Toolbar/CommentBar/index.tsx
  src/views/Me/DraftDetail/PublishButton/index.tsx
  src/views/Me/Settings/Settings/Wallet/index.tsx
  src/views/TagDetail/Buttons/AddButton/CreateDraftMenuItem/index.tsx
Labels: ready

#1680 Fix Onboarding Tasks
  src/common/enums/events.ts
  src/components/Dialogs/RecommendAuthorDialog/index.tsx
  src/components/Dialogs/RecommendTagDialog/index.tsx
  src/components/OnboardingTasks/Dialog/index.tsx
  src/components/OnboardingTasks/NavBar/index.tsx
  src/components/OnboardingTasks/Tasks/index.tsx
  src/components/OnboardingTasks/Widget/index.tsx
Labels: ready

#1681 fix(onboarding-tasks): fix unable to close onboarding tasks
  src/components/ClientUpdater/index.tsx
Labels: ready

#1685 chore(release): v3.19.0
  package.json
Labels: ready

#1688 feat(onboarding): reopen selected tag feed for onboarding task
  src/components/Dialogs/RecommendTagDialog/index.tsx
Labels: ready

#1694 fix(form): rollback formik to 2.1.x
  package-lock.json
  package.json
  src/components/Forms/PaymentForm/PayTo/Confirm/index.tsx
Labels: ready

#1695 fix(form): rollback formik to 2.1.x
  package-lock.json
  package.json
  src/components/Forms/PaymentForm/PayTo/Confirm/index.tsx
Labels: ready

#1696 feat(donation): unify donation icons
  src/components/Forms/PaymentForm/PayTo/Complete/index.tsx
  src/components/Icon/IconHeart.tsx
  src/components/Icon/icons/heart.svg
  src/components/Icon/index.tsx
  src/components/Transaction/Action/index.tsx
  src/components/Transaction/Action/styles.css
  src/views/ArticleDetail/Donation/DonationButton/index.tsx
  src/views/ArticleDetail/Donation/DonationButton/styles.css
Labels: ready

#1693 Refactor: merge notices that have same entities
  src/common/gql/fragmentTypes.json
  src/components/Notice/ArticleArticleNotice/ArticleNewCollectedNotice.tsx
  src/components/Notice/ArticleArticleNotice/index.tsx
  src/components/Notice/ArticleNotice/ArticleMentionedYouNotice.tsx
  src/components/Notice/ArticleNotice/ArticleNewAppreciationNotice.tsx
  src/components/Notice/ArticleNotice/ArticleNewSubscriberNotice.tsx
  src/components/Notice/ArticleNotice/ArticlePublishedNotice.tsx
  src/components/Notice/ArticleNotice/RevisedArticleNotPublishedNotice.tsx
  src/components/Notice/ArticleNotice/RevisedArticlePublishedNotice.tsx
  src/components/Notice/ArticleNotice/index.tsx
  src/components/Notice/ArticleTagNotice/ArticleTagAddedNotice.tsx
  src/components/Notice/ArticleTagNotice/ArticleTagRemovedNotice.tsx
  src/components/Notice/ArticleTagNotice/ArticleTagUnselectedNotice.tsx
  src/components/Notice/ArticleTagNotice/index.tsx
  src/components/Notice/CommentCommentNotice/CommentNewReplyNotice.tsx
  src/components/Notice/CommentCommentNotice/index.tsx
  src/components/Notice/CommentNotice/ArticleNewCommentNotice.tsx
  src/components/Notice/CommentNotice/CommentMentionedYouNotice.tsx
  src/components/Notice/CommentNotice/CommentPinnedNotice.tsx
  src/components/Notice/CommentNotice/SubscribedArticleNewCommentNotice.tsx
  src/components/Notice/CommentNotice/index.tsx
  src/components/Notice/DownstreamArticleArchivedNotice.tsx
  src/components/Notice/TagNotice/TagAddEditorNotice.tsx
  src/components/Notice/TagNotice/TagAdoptionNotice.tsx
  src/components/Notice/TagNotice/TagLeaveEditorNotice.tsx
  src/components/Notice/TagNotice/TagLeaveNotice.tsx
  src/components/Notice/TagNotice/index.tsx
  src/components/Notice/TransactionNotice/PaymentPayoutNotice.tsx
  src/components/Notice/TransactionNotice/PaymentReceivedDonationNotice.tsx
  src/components/Notice/TransactionNotice/index.tsx
  src/components/Notice/UpstreamArticleArchivedNotice.tsx
  src/components/Notice/UserNewFollowerNotice.tsx
  src/components/Notice/UserNotice/UserNewFollowerNotice.tsx
  src/components/Notice/UserNotice/index.tsx
  src/components/Notice/index.tsx
  src/views/Me/Settings/Notification/index.tsx
Labels: ready

#1698 fix(notice): remove unused `key` of CommentPinnedNotice
  src/components/Notice/ArticleArticleNotice/ArticleNewCollectedNotice.tsx
  src/components/Notice/ArticleNotice/ArticleNewAppreciationNotice.tsx
  src/components/Notice/ArticleNotice/ArticleNewSubscriberNotice.tsx
  src/components/Notice/ArticleTagNotice/ArticleTagAddedNotice.tsx
  src/components/Notice/ArticleTagNotice/ArticleTagRemovedNotice.tsx
  src/components/Notice/ArticleTagNotice/ArticleTagUnselectedNotice.tsx
  src/components/Notice/CommentCommentNotice/CommentNewReplyNotice.tsx
  src/components/Notice/CommentNotice/ArticleNewCommentNotice.tsx
  src/components/Notice/CommentNotice/CommentPinnedNotice.tsx
  src/components/Notice/CommentNotice/SubscribedArticleNewCommentNotice.tsx
  src/components/Notice/TagNotice/TagAddEditorNotice.tsx
  src/components/Notice/TagNotice/TagAdoptionNotice.tsx
  src/components/Notice/TagNotice/TagLeaveEditorNotice.tsx
  src/components/Notice/TagNotice/TagLeaveNotice.tsx
  src/components/Notice/UserNotice/UserNewFollowerNotice.tsx
Labels: ready

#1705 feat(icon): replace support icons; show tx message in tooltip;
  public/static/icons/support.svg
  src/components/Forms/PaymentForm/PayTo/Complete/index.tsx
  src/components/Forms/PaymentForm/PayTo/Complete/styles.css
  src/components/Icon/IconSupport.tsx
  src/components/Icon/index.tsx
  src/components/Transaction/Action/index.tsx
  src/components/Transaction/Amount/index.tsx
  src/components/Transaction/State/index.tsx
  src/components/Transaction/index.tsx
  src/views/ArticleDetail/Donation/DonationButton/index.tsx
  tslint.json
Labels: ready

#1701 chore(release): v3.19.1
  package.json
Labels: ready

#1704 feat(storybook): add <UserDigest> to storybook
  .storybook/preview.js
  package-lock.json
  package.json
  public/static/icons/16px/info.svg
  public/static/icons/dot.svg
  src/components/UserDigest/Rich/index.tsx
  src/stories/EmbedShare.stories.tsx
  src/stories/Icon/Icon.stories.tsx
  src/stories/Icon/IconTable.tsx
  src/stories/Share/EmbedShare.stories.tsx
  src/stories/UserDigest/Mini.stories.tsx
  src/stories/UserDigest/Rich.stories.tsx
  src/stories/placeholders/index.ts
  src/stories/tslint.json
  tslint.json
Labels: ready

#1707 fix(icon): fix support icons
  src/components/Transaction/Action/index.tsx
  src/components/Transaction/index.tsx
Labels: ready

#1709 [hotfix - master] fix(icon): fix notice icons
  src/components/Notice/ArticleNotice/ArticleNewAppreciationNotice.tsx
  src/components/Notice/ArticleNotice/ArticleNewSubscriberNotice.tsx
  src/components/Notice/CommentCommentNotice/CommentNewReplyNotice.tsx
  src/components/Notice/CommentNotice/ArticleNewCommentNotice.tsx
  src/components/Notice/CommentNotice/SubscribedArticleNewCommentNotice.tsx
  src/components/Notice/NoticeTypeIcon.tsx
Labels: ready

#1711 [hotfix - master] fix(style): fix safe area of bottom bars
  src/common/styles/mixins/mixins.css
  src/components/Dialog/Footer/styles.css
  src/components/Layout/NavBar/styles.css
  src/components/Layout/SideFooter/styles.css
  src/components/Layout/styles.css
  src/components/OnboardingTasks/NavBar/index.tsx
  src/components/OnboardingTasks/NavBar/styles.css
  src/views/ArticleDetail/Toolbar/index.tsx
  src/views/ArticleDetail/Toolbar/styles.css
  src/views/ArticleDetail/Wall/styles.css
Labels: ready

#1717 Circle in ArticleDigest
  public/static/images/circle-ad-banner.svg
  src/common/enums/text.ts
  src/components/ArticleDigest/DropdownActions/index.tsx
  src/components/ArticleDigest/Feed/Label/index.tsx
  src/components/ArticleDigest/Feed/Label/styles.css
  src/components/ArticleDigest/Feed/index.tsx
  src/components/ArticleDigest/Feed/styles.css
  src/components/ArticleDigest/FooterActions/Appreciation.tsx
  src/components/ArticleDigest/FooterActions/DonationCount.tsx
  src/components/ArticleDigest/FooterActions/ResponseCount.tsx
  src/components/ArticleDigest/FooterActions/index.tsx
  src/components/Buttons/Bookmark/Subscribe.tsx
  src/components/Buttons/Bookmark/Unsubscribe.tsx
  src/components/Buttons/Bookmark/index.tsx
  src/components/CircleAdBanner/index.tsx
  src/components/CircleAdBanner/styles.css
  src/components/CircleAvatar/index.tsx
  src/components/CircleDigest/Plain/index.tsx
  src/components/CircleDigest/Plain/styles.css
  src/components/CircleDigest/Price/index.tsx
  src/components/CircleDigest/Rich/index.tsx
  src/components/CircleDigest/index.tsx
  src/components/Icon/IconCircle16.tsx
  src/components/Icon/IconCircle24.tsx
  src/components/Icon/index.tsx
  src/stories/components/ArticleDigest/Feed.stories.tsx
  src/stories/components/CircleAdBanner/index.stories.tsx
  src/stories/components/CircleDigest/Plain.stories.tsx
  src/stories/components/CircleDigest/Rich.stories.tsx
  src/stories/components/Wall/index.stories.tsx
  src/stories/mocks/index.ts
  src/views/ArticleDetail/Toolbar/DonationButton/index.tsx
  src/views/Home/index.tsx
Labels: 3 pt, ready

#1718 feat(route): add support for path resolving of circle detail page
  src/common/enums/route.ts
  src/common/utils/route.ts
  src/components/Layout/SideNav/index.tsx
  src/components/UserProfile/index.tsx
  src/pages/[name]/[mediaHash].tsx
  src/pages/[name]/comments.tsx
  src/pages/[name]/followees.tsx
  src/pages/[name]/followers.tsx
  src/pages/[name]/index.tsx
  src/pages/[name]/tags.tsx
  src/pages/[userName]/index.tsx
  src/views/User/Articles/UserArticles.tsx
  src/views/User/Comments/UserComments.tsx
  src/views/User/Followees/UserFollowees.tsx
  src/views/User/FollowerTabs/index.tsx
  src/views/User/Followers/UserFollowers.tsx
  src/views/User/Tags/UserTags.tsx
  src/views/User/UserTabs/index.tsx
Labels: 2 pt, ready
