Repository thematters/matters-web, pull requests merged in 2021-04, with the labels that each got.

#1945 chore(release): v3.21.0
  package-lock.json
  package.json
Labels: ready

#1960 fix(badge): fix badge is undefined in user digest placeholder
  src/components/Avatar/index.tsx
Labels: ready

#1957 chore(deps): update deps
  next.config.js
  package-lock.json
  package.json
  src/common/utils/route.ts
  src/components/ArticleDigest/DropdownActions/ExtendButton.tsx
  src/components/Buttons/Write/index.tsx
  src/components/Dialog/Dialog.tsx
  src/components/Dialogs/TagDialog/Content.tsx
  src/components/Editor/SetCoverDialog/index.tsx
  src/components/Editor/Sidebar/index.tsx
  src/components/Forms/CreateCircleForm/Profile.tsx
  src/components/Interaction/Card/index.tsx
  src/components/Layout/UnreadIcon/index.tsx
  src/components/OnboardingTasks/Tasks/index.tsx
  src/components/Search/SearchBar/index.tsx
  src/pages/_app.tsx
  src/views/ArticleDetail/EditMode/PublishState/PublishedState.tsx
  src/views/Home/Sidebar/index.tsx
  src/views/OAuth/Callback/Failure/index.tsx
  src/views/OAuth/Callback/Success/index.tsx
  src/views/Pay/Callback/Failure/index.tsx
  src/views/Pay/Callback/Success/index.tsx
  src/views/Search/index.tsx
  src/views/TagDetail/Buttons/AddButton/CreateDraftMenuItem/index.tsx
Labels: ready

#1962 fix(dialog): add `hasFixed` prop to Dialog.Content
  src/components/Dialog/Content/index.tsx
  src/components/Dialog/Content/styles.css
  src/components/Dialog/Message/index.tsx
Labels: ready

#1963 fix(invitation): add an inner scroll for invitee list
  src/views/Circle/Settings/ManageInvitation/AddInvitationDialog/PreSend.tsx
Labels: ready

#1967 feat(at): add search exclude for @ user
  src/components/Editor/Article/index.tsx
  src/components/GQL/queries/searchUsers.ts
Labels: ready

#1966 Article access control
  public/static/icons/16px/paywall.svg
  src/common/enums/text.ts
  src/common/styles/utils/details.css
  src/components/ArticleDigest/DropdownActions/AddCircleArticle/Button.tsx
  src/components/ArticleDigest/DropdownActions/AddCircleArticle/Dialog.tsx
  src/components/ArticleDigest/DropdownActions/AddCircleArticle/index.tsx
  src/components/ArticleDigest/DropdownActions/index.tsx
  src/components/ArticleDigest/Feed/AccessLabel.tsx
  src/components/ArticleDigest/Feed/Label/styles.css
  src/components/ArticleDigest/Feed/LimitedFree.tsx
  src/components/ArticleDigest/Feed/gql.ts
  src/components/ArticleDigest/Feed/index.tsx
  src/components/Editor/BottomBar/MoreActions/Dialog.tsx
  src/components/Editor/BottomBar/MoreActions/index.tsx
  src/components/Editor/BottomBar/index.tsx
  src/components/Editor/Sidebar/Management/index.tsx
  src/components/Editor/ToggleAccess/index.tsx
  src/components/Editor/ToggleAccess/styles.css
  src/components/Editor/ToggleCircle/index.tsx
  src/components/Editor/ToggleCircle/styles.css
  src/components/GQL/mutations/putCircleArticles.ts
  src/components/Icon/IconPaywall16.tsx
  src/components/Icon/index.tsx
  src/components/Notice/ArticleNotice/CircleNewArticle.tsx
  src/components/Switch/styles.css
  src/stories/mocks/index.ts
  src/views/ArticleDetail/EditMode/Header/index.tsx
  src/views/ArticleDetail/EditMode/gql.ts
  src/views/ArticleDetail/EditMode/index.tsx
  src/views/ArticleDetail/MetaInfo/FingerprintButton/index.tsx
  src/views/ArticleDetail/MetaInfo/TranslationButton/index.tsx
  src/views/ArticleDetail/MetaInfo/gql.ts
  src/views/ArticleDetail/MetaInfo/index.tsx
  src/views/ArticleDetail/MetaInfo/styles.css
  src/views/ArticleDetail/SupportWidget/gql.ts
  src/views/ArticleDetail/SupportWidget/index.tsx
  src/views/ArticleDetail/gql.ts
  src/views/ArticleDetail/index.tsx
  src/views/ArticleDetail/styles.css
  src/views/Circle/Profile/AddCircleArticle/Button.tsx
  src/views/Circle/Profile/AddCircleArticle/Dialog/Content.tsx
  src/views/Circle/Profile/AddCircleArticle/Dialog/index.tsx
  src/views/Circle/Profile/AddCircleArticle/Dialog/styles.css
  src/views/Me/DraftDetail/BottomBar.tsx
  src/views/Me/DraftDetail/Sidebar.tsx
  src/views/Me/DraftDetail/gql.ts
  src/views/Me/DraftDetail/hooks.ts
Labels: 5 pt, ready

#1969 feat(search): add exclude param for searching articles
  src/components/Dialogs/SearchSelectDialog/index.tsx
  src/components/Editor/BottomBar/index.tsx
  src/components/Editor/Sidebar/Collection/index.tsx
  src/components/SearchSelect/SearchingArea/gql.ts
  src/components/SearchSelect/SearchingArea/index.tsx
Labels: ready

#1973 feat(article): use `Article.revisionCount`
  src/views/ArticleDetail/EditMode/Header/index.tsx
  src/views/ArticleDetail/EditMode/gql.ts
  src/views/ArticleDetail/EditMode/index.tsx
Labels: ready

#1976 feat(block): revise text description in block dialog
  src/components/BlockUser/Dialog/index.tsx
Labels: ready

#1979 fix(circle): fix missing save button on circle management dialog
  public/static/manifest.json
  src/components/Editor/BottomBar/MoreActions/Dialog.tsx
  src/components/Head/index.tsx
Labels: ready

#1980 feat(block): disable extend button in article belonged to user who blocked viewer
  src/views/ArticleDetail/index.tsx
Labels: ready

#1981 fix(invitation): fix wrong connection path in circle invitation list
  src/views/Circle/Settings/ManageInvitation/Invitations/index.tsx
Labels: ready

#1983 feat(kill-features): kill view mode
  public/static/icons/24px/view-mode-comfortable.svg
  public/static/icons/24px/view-mode-compact.svg
  public/static/icons/24px/view-mode-default.svg
  src/common/enums/storage.ts
  src/common/enums/text.ts
  src/common/utils/resolvers/clientPreference.ts
  src/common/utils/types/index.ts
  src/components/ArticleDigest/Feed/index.tsx
  src/components/ArticleDigest/Feed/styles.css
  src/components/ClientUpdater/index.tsx
  src/components/GQL/queries/clientPreference.ts
  src/components/Icon/IconViewModeComfortable24.tsx
  src/components/Icon/IconViewModeCompact24.tsx
  src/components/Icon/IconViewModeDefault24.tsx
  src/components/Icon/index.tsx
  src/views/Follow/FollowFeed/DonationsFeed/index.tsx
  src/views/Follow/FollowFeed/FollowComment/index.tsx
  src/views/Home/Feed/index.tsx
  src/views/Me/Settings/Settings/UI/ViewMode.tsx
  src/views/Me/Settings/Settings/UI/index.tsx
Labels: ready

#1988 chore(deps): update `react-spring`
  package-lock.json
  package.json
  src/components/Dialog/Dialog.tsx
  src/components/Layout/Header/MeButton/SideDrawerNav/index.tsx
Labels: ready

#1993 Update deps
  .husky/.gitignore
  .husky/pre-commit
  .husky/prepare-commit-msg
  package-lock.json
  package.json
  src/views/ArticleDetail/AppreciationButton/index.tsx
Labels: ready

#1400 docs(readme): fix copy env command in docker section
  README.md
Labels: bug

#2006 fix(asset): local update draft assets if uploaded completely instead of refetch
  src/components/Editor/SetCoverDialog/Uploader.tsx
  src/components/GQL/updates/draftAssets.ts
Labels: ready

#2008 feat(cover): add fallback cover logic to set cover dialog
  package-lock.json
  package.json
  src/components/Editor/SetCoverDialog/index.tsx
Labels: ready

#2010 fix(style): revise word break on about us hero; fix layout of dialogs;
  public/static/images/intro.jpg
  src/components/Dialog/styles.css
  src/components/Dialogs/PaymentPointerDialog/Explainer/index.tsx
  src/components/Form/List/styles.css
  src/views/About/Hero/index.tsx
  src/views/Me/Wallet/Buttons/styles.css
Labels: ready

#2011 feat(deps): upgrade next.js to 10.2.0
  package-lock.json
  package.json
Labels: ready
