Repository thematters/matters-web, pull requests merged in 2021-07, with the labels that each got.

#2092 Following feed components
  package-lock.json
  package.json
  src/common/styles/mixins.css
  src/components/ArticleDigest/Card/gql.ts
  src/components/ArticleDigest/Card/index.tsx
  src/components/ArticleDigest/DropdownActions/index.tsx
  src/components/ArticleDigest/Feed/AccessLabel.tsx
  src/components/ArticleDigest/Feed/CreatedAt.tsx
  src/components/ArticleDigest/Feed/FollowButton/index.tsx
  src/components/ArticleDigest/Feed/FooterActions/ResponseCount.tsx
  src/components/ArticleDigest/Feed/FooterActions/gql.ts
  src/components/ArticleDigest/Feed/FooterActions/index.tsx
  src/components/ArticleDigest/Feed/FooterActions/styles.css
  src/components/ArticleDigest/Feed/InactiveState.tsx
  src/components/ArticleDigest/Feed/Label/index.tsx
  src/components/ArticleDigest/Feed/Label/styles.css
  src/components/ArticleDigest/Feed/gql.ts
  src/components/ArticleDigest/Feed/index.tsx
  src/components/ArticleDigest/Feed/styles.css
  src/components/ArticleDigest/FooterActions/Appreciation.tsx
  src/components/ArticleDigest/FooterActions/DonationCount.tsx
  src/components/ArticleDigest/FooterActions/index.tsx
  src/components/ArticleDigest/FooterActions/styles.css
  src/components/ArticleDigest/Title/index.tsx
  src/components/ArticleDigest/Title/styles.css
  src/components/CircleDigest/Plain/index.tsx
  src/components/CircleDigest/Plain/styles.css
  src/components/CircleInvitation/styles.css
  src/components/DateTime/index.tsx
  src/components/DateTime/styles.css
  src/components/Tag/index.tsx
  src/components/Tag/styles.css
  src/components/Transaction/index.tsx
  src/components/UserDigest/Plain/gql.ts
  src/components/UserDigest/Plain/index.tsx
  src/components/UserDigest/index.tsx
  src/stories/components/ArticleDigest/Feed.stories.tsx
  src/stories/components/FollowFeed/Feed.tsx
  src/stories/components/FollowFeed/index.stories.tsx
  src/stories/mocks/index.ts
  src/views/ArticleDetail/MetaInfo/gql.ts
  src/views/ArticleDetail/MetaInfo/index.tsx
  src/views/ArticleDetail/Toolbar/index.tsx
  src/views/Circle/Works/Works.tsx
  src/views/Follow/FollowFeed/ArticlesFeed/index.tsx
  src/views/Follow/FollowFeed/DonationsFeed/index.tsx
  src/views/Follow/FollowFeed/FollowFeedCircle/gql.ts
  src/views/Follow/FollowFeed/FollowFeedCircle/index.tsx
  src/views/Follow/FollowFeed/FollowFeedCircle/styles.css
  src/views/Follow/FollowFeed/FollowFeedComment/gql.ts
  src/views/Follow/FollowFeed/FollowFeedComment/index.tsx
  src/views/Follow/FollowFeed/FollowFeedComment/styles.css
  src/views/Follow/FollowFeed/FollowFeedHead/index.tsx
  src/views/Follow/FollowFeed/FollowFeedHead/styles.css
  src/views/Follow/FollowFeed/FollowFeedUser/gql.ts
  src/views/Follow/FollowFeed/FollowFeedUser/index.tsx
  src/views/Follow/FollowFeed/FollowFeedUser/styles.css
  src/views/Follow/FollowFeed/TagsFeed/index.tsx
  src/views/Home/Feed/index.tsx
Labels: storybook

#2115 feat(component): show total read time on article feed
  package-lock.json
  public/static/icons/12px/read-time.svg
  src/components/ArticleDigest/Feed/FooterActions/ReadTime/gql.ts
  src/components/ArticleDigest/Feed/FooterActions/ReadTime/index.tsx
  src/components/ArticleDigest/Feed/FooterActions/gql.ts
  src/components/ArticleDigest/Feed/FooterActions/index.tsx
  src/components/Icon/IconReadTime12.tsx
  src/components/Icon/index.tsx
  src/stories/mocks/index.ts
Labels: ready, storybook

#2120 [hotfix - master] fix(dialog): fix a typo that makes edit username dialog unable to popup
  src/components/Dialogs/TagEditorDialog/index.tsx
  src/views/Me/Settings/Settings/Account/index.tsx
Labels: ready

#2124 feat(tag): change permission of official tag
  src/common/enums/errorCode.ts
  src/common/enums/text.ts
  src/common/gql/fragmentTypes.json
  src/views/TagDetail/gql.ts
  src/views/TagDetail/index.tsx
Labels: ready

#2134 revert(tag): hide new feature
  src/views/TagDetail/index.tsx
Labels: ready

#2138 feat(tag): reopen matty's permission
  src/views/TagDetail/index.tsx
Labels: ready

#2142 fix(superlike): throw error when superlike failed
  src/views/ArticleDetail/AppreciationButton/index.tsx
Labels: ready
