Repository thematters/matters-web, pull requests merged in 2021-03, with the labels that each got.

#1838 fix(discussion): hide upvote and downvote from discussion comments
  src/components/Comment/FooterActions/index.tsx
  src/components/Comment/ThreadComment/index.tsx
  src/views/Circle/Discussion/index.tsx
Labels: ready

#1839 fix(circle): fix incorrect rendering on circle detail pages
  src/common/enums/text.ts
  src/views/Circle/Broadcast/gql.ts
  src/views/Circle/Broadcast/index.tsx
  src/views/Circle/Detail/Profile/FollowButton/Follow.tsx
  src/views/Circle/Detail/Profile/FollowButton/Unfollow.tsx
  src/views/Circle/Detail/Profile/FollowButton/index.tsx
  src/views/Circle/Detail/Profile/gql.ts
  src/views/Circle/Detail/gql.ts
  src/views/Circle/Detail/index.tsx
  src/views/Circle/Discussion/Wall.tsx
  src/views/Circle/Discussion/gql.ts
  src/views/Circle/Discussion/index.tsx
  src/views/Circle/SubscriptionBanner/IntroDialog/index.tsx
  src/views/Circle/SubscriptionBanner/IntroDialog/styles.css
  src/views/Circle/SubscriptionBanner/gql.ts
  src/views/Circle/SubscriptionBanner/index.tsx
  src/views/Circle/SubscriptionBanner/styles.css
  src/views/Circle/Works/gql.ts
  src/views/Circle/Works/index.tsx
Labels: ready

#1847 fix(circle): fix circle cover width; adjust circle price range;
  src/common/enums/payment.ts
  src/components/CircleCover/styles.css
  src/components/Forms/CreateCircleForm/styles.css
Labels: ready

#1829 feat(circle): mailto links for circle banner
  src/views/Home/CircleBanner/applicationLinks.ts
  src/views/Home/CircleBanner/gql.ts
  src/views/Home/CircleBanner/index.tsx
  src/views/Home/CircleBanner/styles.css
Labels: ready

#1849 feat(amount): unify amount enums with server
  src/common/enums/payment.ts
  src/common/utils/form/validate.ts
  src/components/Forms/CreateCircleForm/Init.tsx
  src/components/Forms/PaymentForm/AddCredit/index.tsx
  src/components/Forms/PaymentForm/Payout/Confirm.tsx
Labels: ready

#1850 Fix Circle Detail
  src/views/ArticleDetail/Wall/Circle/styles.css
  src/views/ArticleDetail/index.tsx
  src/views/ArticleDetail/styles.css
  src/views/Circle/Broadcast/index.tsx
  src/views/Circle/Discussion/index.tsx
  src/views/Circle/Works/gql.ts
  src/views/Circle/Works/index.tsx
  src/views/TagDetail/Articles/index.tsx
  src/views/TagDetail/Community/Participants/index.tsx
Labels: ready

#1852 Lock article/comment actions if viewer isn't circle member
  src/components/ArticleDigest/DropdownActions/index.tsx
  src/components/Comment/Feed/index.tsx
  src/components/Comment/FooterActions/index.tsx
  src/components/Comment/ThreadComment/index.tsx
  src/views/ArticleDetail/AppreciationButton/index.tsx
  src/views/ArticleDetail/Responses/FeaturedComments/index.tsx
  src/views/ArticleDetail/Responses/LatestResponses/index.tsx
  src/views/ArticleDetail/Responses/index.tsx
  src/views/ArticleDetail/Toolbar/CommentBar/index.tsx
  src/views/ArticleDetail/Toolbar/DonationButton/index.tsx
  src/views/ArticleDetail/Toolbar/index.tsx
  src/views/ArticleDetail/index.tsx
  src/views/Circle/Broadcast/index.tsx
Labels: ready

#1853 Show brief on discussion wall
  src/views/Circle/Discussion/Wall.tsx
  src/views/Circle/Discussion/index.tsx
  src/views/Circle/Discussion/styles.css
Labels: ready

#1848 feat(summary): add summary support for article detail
  src/common/styles/utils/content.article.css
  src/views/ArticleDetail/CustomizedSummary/index.tsx
  src/views/ArticleDetail/CustomizedSummary/styles.css
  src/views/ArticleDetail/gql.ts
  src/views/ArticleDetail/index.tsx
Labels: ready

#1858 fix(circle): fix `hasPin` on comment actions; grow `<CircleDigest.Mini>`;
  src/components/CircleDigest/Mini/styles.css
  src/components/Comment/DropdownActions/index.tsx
  src/components/Comment/Feed/index.tsx
Labels: ready

#1862 feat(following): revise following dialog
  src/components/UserProfile/FolloweesDialog/gql.ts
  src/components/UserProfile/FollowingDialog/CirclesFeed/gql.tsx
  src/components/UserProfile/FollowingDialog/CirclesFeed/index.tsx
  src/components/UserProfile/FollowingDialog/Content/index.tsx
  src/components/UserProfile/FollowingDialog/FeedType/index.tsx
  src/components/UserProfile/FollowingDialog/TagsFeed/gql.ts
  src/components/UserProfile/FollowingDialog/TagsFeed/index.tsx
  src/components/UserProfile/FollowingDialog/UsersFeed/gql.ts
  src/components/UserProfile/FollowingDialog/UsersFeed/index.tsx
  src/components/UserProfile/FollowingDialog/index.tsx
  src/components/UserProfile/index.tsx
Labels: ready

#1869 fix(summary): add summary checker for publishing button
  src/views/Me/DraftDetail/index.tsx
Labels: ready

#1871 fix(circle): add updater for follow or unfollow
  src/components/Context/Viewer/index.tsx
  src/components/GQL/updates/circleFollowers.ts
  src/views/Circle/Detail/Profile/FollowButton/Follow.tsx
  src/views/Circle/Detail/Profile/FollowButton/Unfollow.tsx
Labels: ready

#1872 chore(editor): update editor version
  package-lock.json
  package.json
Labels: ready

#1870 refactor: circle detail pages
  src/components/GQL/updates/circleFollowers.ts
  src/views/Circle/Broadcast/Broadcast.tsx
  src/views/Circle/Broadcast/gql.ts
  src/views/Circle/Broadcast/index.tsx
  src/views/Circle/Broadcast/styles.css
  src/views/Circle/CircleDetailTabs/index.tsx
  src/views/Circle/Detail/Profile/gql.ts
  src/views/Circle/Detail/Profile/index.tsx
  src/views/Circle/Detail/gql.ts
  src/views/Circle/Detail/index.tsx
  src/views/Circle/Discussion/Discussion.tsx
  src/views/Circle/Discussion/Wall.tsx
  src/views/Circle/Discussion/gql.ts
  src/views/Circle/Discussion/index.tsx
  src/views/Circle/Discussion/styles.css
  src/views/Circle/Profile/AuthorWidget/gql.ts
  src/views/Circle/Profile/AuthorWidget/index.tsx
  src/views/Circle/Profile/AuthorWidget/styles.css
  src/views/Circle/Profile/DropdownActions/gql.ts
  src/views/Circle/Profile/DropdownActions/index.tsx
  src/views/Circle/Profile/EditButton/index.tsx
  src/views/Circle/Profile/FollowButton/Follow.tsx
  src/views/Circle/Profile/FollowButton/Unfollow.tsx
  src/views/Circle/Profile/FollowButton/index.tsx
  src/views/Circle/Profile/FollowersDialog/Content.tsx
  src/views/Circle/Profile/FollowersDialog/gql.ts
  src/views/Circle/Profile/FollowersDialog/index.tsx
  src/views/Circle/Profile/MembersDialog/Content.tsx
  src/views/Circle/Profile/MembersDialog/gql.ts
  src/views/Circle/Profile/MembersDialog/index.tsx
  src/views/Circle/Profile/gql.ts
  src/views/Circle/Profile/index.tsx
  src/views/Circle/Profile/styles.css
  src/views/Circle/Works/Works.tsx
  src/views/Circle/Works/gql.ts
  src/views/Circle/Works/index.tsx
  src/views/Circle/Works/styles.css
  src/views/User/Articles/UserArticles.tsx
  src/views/User/Comments/UserComments.tsx
  src/views/User/Tags/UserTags.tsx
Labels: ready

#1877 fix(circle): show banner for anonymous; hide comment form for blocked user;
  src/components/Comment/Content/styles.css
  src/views/Circle/Discussion/Discussion.tsx
  src/views/Circle/Discussion/gql.ts
  src/views/Home/CircleBanner/gql.ts
  src/views/Home/CircleBanner/index.tsx
Labels: ready

#1878 fix(language): correct text
  src/views/Me/Wallet/PaymentPointer/index.tsx
Labels: ready

#1879 fix(circle): fix wrong `lockActions` in article detail; remove unused fields on fragments;
  src/views/ArticleDetail/gql.ts
  src/views/ArticleDetail/index.tsx
  src/views/Circle/Broadcast/gql.ts
  src/views/Circle/Profile/gql.ts
Labels: ready

#1880 fix(form): revise regex for forma validation
  src/common/utils/form/validate.ts
Labels: ready

#1881 feat(circle): allows to edit circle display name
  src/components/Forms/CreateCircleForm/Profile.tsx
  src/views/Circle/Settings/EditProfile/gql.ts
Labels: ready

#1895 fix(error): display right error code for subscription
  src/common/enums/errorCode.ts
  src/common/enums/text.ts
Labels: ready

#1898 fix(error): add error for circle creation limit
  src/common/enums/errorCode.ts
  src/common/enums/text.ts
Labels: ready

#1900 Replace recommendation.followingTags with following.tags
  src/components/Context/Viewer/index.tsx
  src/components/GQL/updates/viewerFollowingTagCount.ts
  src/views/Follow/FollowFeed/TagsFeed/index.tsx
Labels: ready

#1901 fix(circle): add reserved circle names
  src/common/enums/hardcode.ts
  src/common/enums/index.ts
  src/common/enums/invalidNames.ts
  src/common/utils/form/validate.ts
Labels: ready

#1906 refactor(following): replace user.followees with user.following.users
  src/common/gql/fragmentTypes.json
  src/components/Context/Viewer/index.tsx
  src/components/GQL/updates/viewerFolloweeCount.ts
  src/components/UserProfile/gql.ts
  src/components/UserProfile/index.tsx
  src/views/Follow/PickAuthors/AuthorPicker/index.tsx
  src/views/Follow/index.tsx
Labels: ready

#1907 ci: prevent deployment on pull request
  .github/workflows/deploy.yml
  .github/workflows/storybook.yml
  .github/workflows/test.yml
Labels: storybook

#1909 ci: change `push` to `pull_request` event for deployment
  .github/workflows/deploy.yml
Labels: ready

#1914 feat(circle): local updates on toggle circle broadcast pin status
  src/components/Comment/DropdownActions/PinButton.tsx
  src/components/Comment/DropdownActions/index.tsx
  src/components/GQL/updates/circleBroadcast.ts
  src/components/GQL/updates/tagArticlesCount.ts
  src/components/GQL/updates/userArticles.ts
  src/views/ArticleDetail/Responses/index.tsx
  src/views/Me/AppreciationsReceived/index.tsx
  src/views/Me/AppreciationsSent/index.tsx
  src/views/Me/Transactions/index.tsx
  src/views/OAuth/Authorize/index.tsx
  src/views/TagDetail/Community/Maintainers/index.tsx
  src/views/TagDetail/index.tsx
  src/views/User/Articles/UserArticles.tsx
  src/views/User/Articles/gql.ts
Labels: ready

#1916 fix(style): bolden circle creation banner
  src/components/Form/List/Item/index.tsx
  src/components/Form/List/Item/styles.css
  src/components/UserProfile/CircleWidget/index.tsx
  src/components/UserProfile/CircleWidget/styles.css
Labels: ready

#1911 Enhance <SearchSelect>
  src/common/enums/text.ts
  src/components/Dialogs/SearchSelectDialog/index.tsx
  src/components/Editor/BottomBar/index.tsx
  src/components/Editor/Sidebar/Tags/index.tsx
  src/components/SearchSelect/SearchSelectNode/User/index.tsx
  src/components/SearchSelect/SearchingArea/InviteEmail/index.tsx
  src/components/SearchSelect/SearchingArea/InviteEmail/styles.css
  src/components/SearchSelect/SearchingArea/SearchInput/index.tsx
  src/components/SearchSelect/SearchingArea/gql.ts
  src/components/SearchSelect/SearchingArea/index.tsx
  src/components/Tag/index.tsx
  src/components/UserDigest/Mini/index.tsx
  src/views/Circle/Profile/DropdownActions/AddCircleArticleDialog/Content.tsx
  src/views/Circle/Profile/DropdownActions/AddCircleArticleDialog/index.tsx
  src/views/Circle/Profile/DropdownActions/index.tsx
  src/views/Me/DraftDetail/BottomBar.tsx
  src/views/Me/DraftDetail/Sidebar.tsx
Labels: ready

#1921 feat(notice): add notice component for circle invitation
  src/common/gql/fragmentTypes.json
  src/components/Notice/CircleNotice/CircleInvitationNotice.tsx
  src/components/Notice/CircleNotice/index.tsx
  src/components/Notice/NoticeCircleCard.tsx
  src/stories/components/Notices/mock.ts
  src/stories/mocks/index.ts
Labels: ready

#1923 feat(invitation): add entrance of invitation list
  src/common/enums/route.ts
  src/common/enums/text.ts
  src/common/styles/mixins.css
  src/common/utils/route.ts
  src/components/CircleInvitation/Invitee.tsx
  src/components/CircleInvitation/Resend.tsx
  src/components/CircleInvitation/index.tsx
  src/components/CircleInvitation/styles.css
  src/components/FreePeriod/index.tsx
  src/components/GQL/mutations/invite.ts
  src/components/index.tsx
  src/pages/[name]/settings/manage-invitation.tsx
  src/views/Circle/Profile/DropdownActions/index.tsx
  src/views/Circle/Settings/ManageInvitation/Invitations/gql.ts
  src/views/Circle/Settings/ManageInvitation/Invitations/index.tsx
  src/views/Circle/Settings/ManageInvitation/Invitations/styles.css
  src/views/Circle/Settings/ManageInvitation/index.tsx
  src/views/Circle/Settings/index.tsx
Labels: ready

#1925 feat(circle): subscribe circle via price button directly
  src/components/CircleDigest/Price/index.tsx
  src/components/Dialogs/AddCreditDialog/index.tsx
  src/components/Dialogs/DonationDialog/index.tsx
  src/components/Dialogs/PayoutDialog/index.tsx
  src/components/Dialogs/ResetPaymentPasswordDialog/index.tsx
  src/components/Dialogs/SubscribeCircleDialog/index.tsx
  src/components/Forms/PaymentForm/AddCredit/index.tsx
  src/components/Forms/PaymentForm/ConnectStripeAccount/index.tsx
  src/components/Forms/PaymentForm/PayTo/index.tsx
  src/components/Forms/PaymentForm/Payout/index.tsx
  src/components/Forms/PaymentForm/Processing/index.tsx
  src/components/Forms/PaymentForm/ResetPassword/index.tsx
  src/components/Forms/PaymentForm/SetPassword/index.tsx
  src/components/Forms/PaymentForm/SubscribeCircle/index.tsx
  src/components/Forms/PaymentForm/index.tsx
  src/components/Forms/index.tsx
  src/components/UserProfile/CircleWidget/index.tsx
  src/views/About/Hero/index.tsx
  src/views/About/Team/index.tsx
  src/views/ArticleDetail/index.tsx
  src/views/Circle/Profile/AddCircleArticle/Button.tsx
  src/views/Home/CircleBanner/index.tsx
  src/views/Home/CircleBanner/styles.css
Labels: ready

#1926 feat(dialog): add dialog for adding circle invitations
  src/common/enums/events.ts
  src/common/enums/text.ts
  src/components/GQL/queries/circleInvitations.ts
  src/components/SearchSelect/SearchingArea/SearchInput/index.tsx
  src/components/SearchSelect/SearchingArea/index.tsx
  src/views/Circle/Settings/ManageInvitation/AddButton/index.tsx
  src/views/Circle/Settings/ManageInvitation/AddInvitationDialog/Option.tsx
  src/views/Circle/Settings/ManageInvitation/AddInvitationDialog/PreSend.tsx
  src/views/Circle/Settings/ManageInvitation/AddInvitationDialog/Search.tsx
  src/views/Circle/Settings/ManageInvitation/AddInvitationDialog/Sent.tsx
  src/views/Circle/Settings/ManageInvitation/AddInvitationDialog/gql.ts
  src/views/Circle/Settings/ManageInvitation/AddInvitationDialog/index.tsx
  src/views/Circle/Settings/ManageInvitation/Invitations/index.tsx
  src/views/Circle/Settings/ManageInvitation/index.tsx
Labels: ready

#1929 feat(subscription): add trial discount info for circle invitation
  src/components/CircleDigest/Price/index.tsx
  src/components/Dialogs/SubscribeCircleDialog/index.tsx
  src/components/Forms/PaymentForm/ConfirmTable/index.tsx
  src/components/Forms/PaymentForm/ConfirmTable/styles.css
  src/components/Forms/PaymentForm/SubscribeCircle/CardPayment.tsx
  src/components/Forms/PaymentForm/SubscribeCircle/Head.tsx
  src/components/Forms/PaymentForm/SubscribeCircle/PasswordPayment.tsx
  src/components/Forms/PaymentForm/SubscribeCircle/index.tsx
  src/stories/mocks/index.ts
  src/views/Circle/SubscriptionBanner/gql.ts
Labels: ready

#1935 feat(about): make report items draggable
  package-lock.json
  package.json
  public/static/images/about/team-beryl.svg
  src/views/About/Hero/index.tsx
  src/views/About/Hero/styles.css
  src/views/About/Intro/index.tsx
  src/views/About/Intro/styles.css
  src/views/About/Stats/index.tsx
  src/views/About/Team/index.tsx
Labels: ready

#1941 fix(subscribe): replace text of subscribe button with free trial if user is invited
  src/views/Circle/SubscriptionBanner/index.tsx
Labels: bug
